const DATA_KEY = "avitjet.settings";

type AvitjetSettings = {
  grid: number;
  stroke: number;
  segmentsVisible: boolean;
};

figma.showUI(__html__, { width: 320, height: 300 });

figma.ui.onmessage = async (msg: { type: string; grid?: number; stroke?: number; segments?: boolean }) => {
  if (msg.type !== "create") {
    return;
  }

  const grid = msg.grid ?? 0;
  const stroke = msg.stroke ?? 0;
  const segmentsVisible = Boolean(msg.segments);

  if (!Number.isInteger(grid) || grid < 2) {
    figma.notify("Grid step must be an integer ≥ 2");
    return;
  }

  if (![grid, grid * 2].includes(stroke)) {
    figma.notify("Stroke must be 1G or 2G");
    return;
  }

  try {
    const component = createAvitjetComponent({ grid, stroke, segmentsVisible });
    figma.currentPage.selection = [component];
    figma.viewport.scrollAndZoomIntoView([component]);
    figma.notify("Avitjet component created");
  } catch (error) {
    if (error instanceof Error) {
      figma.notify(`Failed to create component: ${error.message}`);
    } else {
      figma.notify("Failed to create component");
    }
  }
};

figma.on("documentchange", (event) => {
  for (const change of event.documentChanges) {
    if (change.type !== "PROPERTY_CHANGE") continue;
    if (!change.properties.includes("width") && !change.properties.includes("height")) continue;

    const node = change.node as SceneNode | null;
    if (!node || node.type !== "COMPONENT") continue;

    const settings = readPluginData(node);
    if (!settings) continue;

    updateAvitjetComponent(node, settings);
  }
});

function createAvitjetComponent(settings: AvitjetSettings): ComponentNode {
  const { grid, stroke, segmentsVisible } = settings;
  const component = figma.createComponent();
  const baseSize = 8 * grid;
  component.resizeWithoutConstraints(baseSize, baseSize);
  component.name = `Avitjet/G=${grid}/Stroke=${stroke / grid}G/Segments=${segmentsVisible ? "On" : "Off"}`;
  component.description = "Generated by Avitjet Builder";

  writePluginData(component, settings);

  const border = createBorderVector(component.width, component.height, settings);
  component.appendChild(border);
  writePluginData(border, settings);

  const content = createContentFrame(component, settings);
  component.appendChild(content);
  writePluginData(content, settings);

  applySegments(component, settings);

  updateAvitjetComponent(component, settings);

  return component;
}

function createBorderVector(width: number, height: number, settings: AvitjetSettings): VectorNode {
  const border = figma.createVector();
  border.name = "Border";
  border.strokes = [{ type: "SOLID", color: { r: 0, g: 0, b: 0 } }];
  border.strokeWeight = settings.stroke;
  border.strokeAlign = "INSIDE";
  border.fills = [];
  border.resizeWithoutConstraints(width, height);
  border.vectorPaths = [
    {
      windingRule: "NONZERO",
      data: makeAvitjetPath(width, height, computeRadius(width, height, settings.grid)),
    },
  ];
  return border;
}

function createContentFrame(component: ComponentNode, settings: AvitjetSettings): FrameNode {
  const { grid, stroke } = settings;
  const frame = figma.createFrame();
  frame.name = "Content";
  frame.layoutMode = "VERTICAL";
  frame.primaryAxisSizingMode = "FIXED";
  frame.counterAxisSizingMode = "FIXED";
  frame.itemSpacing = grid * 0.5;
  frame.paddingLeft = grid;
  frame.paddingRight = grid;
  frame.paddingTop = grid;
  frame.paddingBottom = grid;
  frame.fills = [];
  frame.strokeAlign = "INSIDE";
  frame.strokes = [];
  const inner = computeInnerSize(component.width, component.height, stroke);
  frame.resizeWithoutConstraints(inner.width, inner.height);
  frame.x = stroke;
  frame.y = stroke;
  return frame;
}

function applySegments(component: ComponentNode, settings: AvitjetSettings): void {
  let group = component.findOne((node) => node.type === "GROUP" && node.name === "ColorSegments") as GroupNode | null;

  if (!group) {
    const diameter = 2 * settings.grid;
    const ellipse = figma.createEllipse();
    ellipse.name = "SegmentCircle";
    ellipse.resizeWithoutConstraints(diameter, diameter);
    ellipse.fills = [{ type: "SOLID", color: { r: 0.1, g: 0.6, b: 0.9 } }];
    ellipse.strokes = [];
    ellipse.x = 0;
    ellipse.y = 0;
    ellipse.constraints = { horizontal: "MAX", vertical: "MAX" };

    component.appendChild(ellipse);
    group = figma.group([ellipse], component);
    group.name = "ColorSegments";
  }

  updateSegments(group, component, settings);
  group.visible = settings.segmentsVisible;
  writePluginData(group, settings);
}

function updateSegments(group: GroupNode, component: ComponentNode, settings: AvitjetSettings): void {
  const diameter = 2 * settings.grid;
  let ellipse = group.findOne((node) => node.type === "ELLIPSE") as EllipseNode | null;
  if (!ellipse) {
    ellipse = figma.createEllipse();
    ellipse.name = "SegmentCircle";
    ellipse.fills = [{ type: "SOLID", color: { r: 0.1, g: 0.6, b: 0.9 } }];
    ellipse.strokes = [];
    group.appendChild(ellipse);
  }
  if (ellipse.width !== diameter || ellipse.height !== diameter) {
    ellipse.resizeWithoutConstraints(diameter, diameter);
  }
  const offset = settings.grid;
  const x = alignToGrid(component.width - settings.stroke - diameter - offset, settings.grid);
  const y = alignToGrid(component.height - settings.stroke - diameter - offset, settings.grid);
  group.x = Math.max(settings.stroke, x);
  group.y = Math.max(settings.stroke, y);
  ellipse.x = 0;
  ellipse.y = 0;
  writePluginData(ellipse, settings);
}

function updateAvitjetComponent(component: ComponentNode, settings: AvitjetSettings): void {
  const desired = computeClampSize(component.width, component.height, settings);
  if (desired.width !== component.width || desired.height !== component.height) {
    component.resizeWithoutConstraints(desired.width, desired.height);
  }

  const border = component.findOne((node) => node.type === "VECTOR" && node.name === "Border") as VectorNode | null;
  if (border) {
    border.resizeWithoutConstraints(component.width, component.height);
    border.strokeWeight = settings.stroke;
    border.strokeAlign = "INSIDE";
    border.fills = [];
    border.vectorPaths = [
      {
        windingRule: "NONZERO",
        data: makeAvitjetPath(component.width, component.height, computeRadius(component.width, component.height, settings.grid)),
      },
    ];
    writePluginData(border, settings);
  }

  const content = component.findOne((node) => node.type === "FRAME" && node.name === "Content") as FrameNode | null;
  if (content) {
    const inner = computeInnerSize(component.width, component.height, settings.stroke);
    content.resizeWithoutConstraints(inner.width, inner.height);
    content.x = settings.stroke;
    content.y = settings.stroke;
    content.itemSpacing = settings.grid * 0.5;
    content.paddingLeft = settings.grid;
    content.paddingRight = settings.grid;
    content.paddingTop = settings.grid;
    content.paddingBottom = settings.grid;
    writePluginData(content, settings);
  }

  const segmentsGroup = component.findOne((node) => node.type === "GROUP" && node.name === "ColorSegments") as GroupNode | null;
  if (segmentsGroup) {
    segmentsGroup.visible = settings.segmentsVisible;
    if (settings.segmentsVisible) {
      updateSegments(segmentsGroup, component, settings);
    }
    writePluginData(segmentsGroup, settings);
  } else if (settings.segmentsVisible) {
    applySegments(component, settings);
  }

  component.name = `Avitjet/G=${settings.grid}/Stroke=${settings.stroke / settings.grid}G/Segments=${settings.segmentsVisible ? "On" : "Off"}`;
  writePluginData(component, settings);
}

function readPluginData(node: BaseNode & PluginDataMixin): AvitjetSettings | null {
  const raw = node.getPluginData(DATA_KEY);
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as Partial<AvitjetSettings>;
    if (typeof parsed.grid !== "number" || typeof parsed.stroke !== "number" || typeof parsed.segmentsVisible !== "boolean") {
      return null;
    }
    return { grid: parsed.grid, stroke: parsed.stroke, segmentsVisible: parsed.segmentsVisible };
  } catch {
    return null;
  }
}

function writePluginData(node: BaseNode & PluginDataMixin, settings: AvitjetSettings): void {
  node.setPluginData(DATA_KEY, JSON.stringify(settings));
}

function makeAvitjetPath(width: number, height: number, radius: number): string {
  const r = Number(radius.toFixed(2));
  const w = Number(width.toFixed(2));
  const h = Number(height.toFixed(2));
  return [
    `M ${w - r} 0`,
    `A ${r} ${r} 0 0 1 ${w} ${r}`,
    `L ${w} ${h - r}`,
    `A ${r} ${r} 0 0 1 ${w - r} ${h}`,
    `L ${r} ${h}`,
    `A ${r} ${r} 0 0 1 0 ${h - r}`,
    `L 0 ${r}`,
    `A ${r} ${r} 0 0 1 ${r} 0`,
    "Z",
  ].join(" ");
}

function computeClampSize(width: number, height: number, settings: AvitjetSettings): { width: number; height: number } {
  const { grid, stroke } = settings;
  const minInner = 4 * grid;
  const minSize = minInner + 2 * stroke;

  let w = Math.max(width, minSize);
  let h = Math.max(height, minSize);

  if (w / h > 4) {
    w = h * 4;
  } else if (h / w > 4) {
    h = w * 4;
  }

  w = alignToGrid(w, grid);
  h = alignToGrid(h, grid);

  w = Math.max(w, minSize);
  h = Math.max(h, minSize);

  return { width: w, height: h };
}

function computeInnerSize(width: number, height: number, stroke: number): { width: number; height: number } {
  return {
    width: Math.max(0, width - 2 * stroke),
    height: Math.max(0, height - 2 * stroke),
  };
}

function computeRadius(width: number, height: number, grid: number): number {
  const minDimension = Math.min(width, height);
  const minRadius = 2 * grid;
  const maxRadius = 4 * grid;
  const half = minDimension / 2;
  return clamp(half, minRadius, maxRadius);
}

function alignToGrid(value: number, grid: number): number {
  return Math.round(value / grid) * grid;
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}
